[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.97
blur = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 300

[colors.bright]
black = "#2C3241"
red = "#E8846C"
green = "#A7B1C1"
yellow = "#FFB4A2"
blue = "#465366"
magenta = "#E8846C"
cyan = "#A7B1C1"
white = "#E6DDD1"

[colors.normal]
black = "#2C3241"
red = "#E8846C"
green = "#A7B1C1"
yellow = "#FFB4A2"
blue = "#465366"
magenta = "#E8846C"
cyan = "#A7B1C1"
white = "#E6DDD1"

[colors.primary]
background = "#1A1A1D"
foreground = "#E6DDD1"

[font]
size = 10.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"
