#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/down.jpg
fi

eftwm-command "UnloadTheme"

pkill picom
pkill trayer
pkill blugon
if [ -x "$(command -v eww)" ]; then
  eww kill
fi
