#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale --no-xinerama $SCRIPTPATH/background.jpg
fi

# Set the theme.toml config
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"

# start eww daemon
eww daemon &
blugon &
picom --config $SCRIPTPATH/picom.conf --experimental-backends &

trayer --edge top --expand false --width 10 --height 28 --align right --monitor 1 --iconspacing 10 --transparent true --tint 0xff2e3444 --alpha 0

eww state
eww open bar0
eww open bar1
