#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale --no-xinerama $SCRIPTPATH/background.jpg
fi

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# start eww daemon
eww daemon &

trayer --edge top --expand false --width 8 --height 32 --align right --monitor 1 --margin 10 --distance 10

#open eww 'bar' windows
#this is a bit of an uggly hack, a more elegant way will hopefully be possible with a future `eww` version
sleep 1
index=0
sizes=( $(leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' ) )
for size in "${sizes[@]}"
do
    eww open bar$index
    let index=index+1
done

eww reload
