#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#if path to liblinkt is not not exported do so:
if [ -z "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
fi

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Fix the cursor being incorrect
xsetroot -cursor_name left_ptr

# start other services
picom --config $SCRIPTPATH/picom.conf &
blugon &

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale --no-xinerama $SCRIPTPATH/background.jpg
fi

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

eww open information

trayer --edge right --expand false --align top --monitor 2 --iconspacing 10 --tint 0xff2C3241 --alpha 100 &
