# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@emacs-grammarly/unofficial-grammarly-api-0.2.2" = {
      name = "_at_emacs-grammarly_slash_unofficial-grammarly-api";
      packageName = "@emacs-grammarly/unofficial-grammarly-api";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emacs-grammarly/unofficial-grammarly-api/-/unofficial-grammarly-api-0.2.2.tgz";
        sha512 = "GKv/FrBSpHcAwLbuNV97uUgFBA8UiUxnYD2HkgCLDdFf+s7NadDI9OGwi5mMWaEjlim8WD/AOmx/gH39SbnI9g==";
      };
    };
    "@flatten-js/interval-tree-1.0.18" = {
      name = "_at_flatten-js_slash_interval-tree";
      packageName = "@flatten-js/interval-tree";
      version = "1.0.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/@flatten-js/interval-tree/-/interval-tree-1.0.18.tgz";
        sha512 = "o72sZErW0Y1C82Cg7nk82ojJ/22EtmKyp5I3eNqgcOKFp/VCzetATYYjJIqOBBaR7FQ/MFj/ZpsmP38mL4TkYA==";
      };
    };
    "@types/mdast-3.0.10" = {
      name = "_at_types_slash_mdast";
      packageName = "@types/mdast";
      version = "3.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/mdast/-/mdast-3.0.10.tgz";
        sha512 = "W864tg/Osz1+9f4lrGTZpCSO5/z4608eUp19tbozkq2HJK6i3z1kT0H9tlADXuYIb1YYOBByU4Jsqkk75q48qA==";
      };
    };
    "@types/unist-2.0.6" = {
      name = "_at_types_slash_unist";
      packageName = "@types/unist";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/unist/-/unist-2.0.6.tgz";
        sha512 = "PBjIUxZHOuj0R15/xuwJYjFi+KZdNFrehocChv4g5hu6aFroHue8m0lBP0POdK2nKzbw0cgV1mws8+V/JAcEkQ==";
      };
    };
    "@vue/reactivity-3.2.31" = {
      name = "_at_vue_slash_reactivity";
      packageName = "@vue/reactivity";
      version = "3.2.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/reactivity/-/reactivity-3.2.31.tgz";
        sha512 = "HVr0l211gbhpEKYr2hYe7hRsV91uIVGFYNHj73njbARVGHQvIojkImKMaZNDdoDZOIkMsBc9a1sMqR+WZwfSCw==";
      };
    };
    "@vue/shared-3.2.31" = {
      name = "_at_vue_slash_shared";
      packageName = "@vue/shared";
      version = "3.2.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/shared/-/shared-3.2.31.tgz";
        sha512 = "ymN2pj6zEjiKJZbrf98UM2pfDd6F2H7ksKw7NDt/ZZ1fh5Ei39X5tABugtT03ZRlWd9imccoK0hE8hpjpU7irQ==";
      };
    };
    "bail-1.0.5" = {
      name = "bail";
      packageName = "bail";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/bail/-/bail-1.0.5.tgz";
        sha512 = "xFbRxM1tahm08yHBP16MMjVUAvDaBMD38zsM9EMAUN61omwLmKlOpB/Zku5QkjZ8TZ4vn53pj+t518cH0S03RQ==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "character-entities-1.2.4" = {
      name = "character-entities";
      packageName = "character-entities";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-entities/-/character-entities-1.2.4.tgz";
        sha512 = "iBMyeEHxfVnIakwOuDXpVkc54HijNgCyQB2w0VfGQThle6NXn50zU6V/u+LDhxHcDUPojn6Kpga3PTAD8W1bQw==";
      };
    };
    "character-entities-legacy-1.1.4" = {
      name = "character-entities-legacy";
      packageName = "character-entities-legacy";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-entities-legacy/-/character-entities-legacy-1.1.4.tgz";
        sha512 = "3Xnr+7ZFS1uxeiUDvV02wQ+QDbc55o97tIV5zHScSPJpcLm/r0DFPcoY3tYRp+VZukxuMeKgXYmsXQHO05zQeA==";
      };
    };
    "character-reference-invalid-1.1.4" = {
      name = "character-reference-invalid";
      packageName = "character-reference-invalid";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-reference-invalid/-/character-reference-invalid-1.1.4.tgz";
        sha512 = "mKKUkUbhPpQlCOfIuZkvSEgktjPFIsZKRRbC6KWVEMvlzblj3i3asQv5ODsrwt0N3pHAEvjP8KTQPHkp0+6jOg==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "debug-4.3.3" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.3.tgz";
        sha512 = "/zxw5+vh1Tfv+4Qn7a5nsbcJKPaSvCDhojn6FEl9vupwK2VCSDtEiEtqr8DFtzYFOdz63LBkxec7DYuc2jon6Q==";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "fast-diff-1.2.0" = {
      name = "fast-diff";
      packageName = "fast-diff";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-diff/-/fast-diff-1.2.0.tgz";
        sha512 = "xJuoT5+L99XlZ8twedaRf6Ax2TgQVxvgZOYoPKqZufmJib0tL2tegPBOZb1pVNgIhlqDlA0eO0c3wBvQcmzx4w==";
      };
    };
    "inversify-5.1.1" = {
      name = "inversify";
      packageName = "inversify";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inversify/-/inversify-5.1.1.tgz";
        sha512 = "j8grHGDzv1v+8T1sAQ+3boTCntFPfvxLCkNcxB1J8qA0lUN+fAlSyYd+RXKvaPRL4AGyPxViutBEJHNXOyUdFQ==";
      };
    };
    "is-alphabetical-1.0.4" = {
      name = "is-alphabetical";
      packageName = "is-alphabetical";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-alphabetical/-/is-alphabetical-1.0.4.tgz";
        sha512 = "DwzsA04LQ10FHTZuL0/grVDk4rFoVH1pjAToYwBrHSxcrBIGQuXrQMtD5U1b0U2XVgKZCTLLP8u2Qxqhy3l2Vg==";
      };
    };
    "is-alphanumerical-1.0.4" = {
      name = "is-alphanumerical";
      packageName = "is-alphanumerical";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-alphanumerical/-/is-alphanumerical-1.0.4.tgz";
        sha512 = "UzoZUr+XfVz3t3v4KyGEniVL9BDRoQtY7tOyrRybkVNjDFWyo1yhXNGrrBTQxp3ib9BLAWs7k2YKBQsFRkZG9A==";
      };
    };
    "is-buffer-2.0.5" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-2.0.5.tgz";
        sha512 = "i2R6zNFDwgEHJyQUtJEk0XFi1i0dPFn/oqjK3/vPCcDeJvW5NQ83V8QbicfF1SupOaB0h8ntgBC2YiE7dfyctQ==";
      };
    };
    "is-decimal-1.0.4" = {
      name = "is-decimal";
      packageName = "is-decimal";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-decimal/-/is-decimal-1.0.4.tgz";
        sha512 = "RGdriMmQQvZ2aqaQq3awNA6dCGtKpiDFcOzrTWrDAT2MiWrKQVPmxLGHl7Y2nNu6led0kEyoX0enY0qXYsv9zw==";
      };
    };
    "is-hexadecimal-1.0.4" = {
      name = "is-hexadecimal";
      packageName = "is-hexadecimal";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-hexadecimal/-/is-hexadecimal-1.0.4.tgz";
        sha512 = "gyPJuv83bHMpocVYoqof5VDiZveEoGoFL8m3BXNb2VW8Xs+rz9kqO8LOQ5DH6EsuvilT1ApazU0pyl+ytbPtlw==";
      };
    };
    "is-plain-obj-2.1.0" = {
      name = "is-plain-obj";
      packageName = "is-plain-obj";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-2.1.0.tgz";
        sha512 = "YWnfyRwxL/+SsrWYfOpUtz5b3YD+nyfkHvjbcanzk8zgyO4ASD67uVMRt8k5bM4lLMDnXfriRhOpemw+NfT1eA==";
      };
    };
    "lodash.clonedeep-4.5.0" = {
      name = "lodash.clonedeep";
      packageName = "lodash.clonedeep";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.clonedeep/-/lodash.clonedeep-4.5.0.tgz";
        sha1 = "e23f3f9c4f8fbdde872529c1071857a086e5ccef";
      };
    };
    "lodash.isequal-4.5.0" = {
      name = "lodash.isequal";
      packageName = "lodash.isequal";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isequal/-/lodash.isequal-4.5.0.tgz";
        sha1 = "415c4478f2bcc30120c22ce10ed3226f7d3e18e0";
      };
    };
    "longest-streak-2.0.4" = {
      name = "longest-streak";
      packageName = "longest-streak";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/longest-streak/-/longest-streak-2.0.4.tgz";
        sha512 = "vM6rUVCVUJJt33bnmHiZEvr7wPT78ztX7rojL+LW51bHtLh6HTjx84LA5W4+oa6aKEJA7jJu5LR6vQRBpA5DVg==";
      };
    };
    "mdast-util-from-markdown-0.8.5" = {
      name = "mdast-util-from-markdown";
      packageName = "mdast-util-from-markdown";
      version = "0.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-from-markdown/-/mdast-util-from-markdown-0.8.5.tgz";
        sha512 = "2hkTXtYYnr+NubD/g6KGBS/0mFmBcifAsI0yIWRiRo0PjVs6SSOSOdtzbp6kSGnShDN6G5aWZpKQ2lWRy27mWQ==";
      };
    };
    "mdast-util-to-markdown-0.6.5" = {
      name = "mdast-util-to-markdown";
      packageName = "mdast-util-to-markdown";
      version = "0.6.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-to-markdown/-/mdast-util-to-markdown-0.6.5.tgz";
        sha512 = "XeV9sDE7ZlOQvs45C9UKMtfTcctcaj/pGwH8YLbMHoMOXNNCn2LsqVQOqrF1+/NU8lKDAqozme9SCXWyo9oAcQ==";
      };
    };
    "mdast-util-to-string-2.0.0" = {
      name = "mdast-util-to-string";
      packageName = "mdast-util-to-string";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-to-string/-/mdast-util-to-string-2.0.0.tgz";
        sha512 = "AW4DRS3QbBayY/jJmD8437V1Gombjf8RSOUCMFBuo5iHi58AGEgVCKQ+ezHkZZDpAQS75hcBMpLqjpJTjtUL7w==";
      };
    };
    "micromark-2.11.4" = {
      name = "micromark";
      packageName = "micromark";
      version = "2.11.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark/-/micromark-2.11.4.tgz";
        sha512 = "+WoovN/ppKolQOFIAajxi7Lu9kInbPxFuTBVEavFcL8eAfVstoc5MocPmqBeAdBOJV00uaVjegzH4+MA0DN/uA==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "node-fetch-2.6.7" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.6.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.7.tgz";
        sha512 = "ZjMPFEfVx5j+y2yF35Kzx5sF7kDzxuDj6ziH4FFbOp87zKDZNx8yExJIb05OGF4Nlt9IHFIMBkRl41VdvcNdbQ==";
      };
    };
    "parse-entities-2.0.0" = {
      name = "parse-entities";
      packageName = "parse-entities";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-entities/-/parse-entities-2.0.0.tgz";
        sha512 = "kkywGpCcRYhqQIchaWqZ875wzpS/bMKhz5HnN3p7wveJTkTtyAB/AlnS0f8DFSqYW1T82t6yEAkEcB+A1I3MbQ==";
      };
    };
    "quill-delta-4.2.2" = {
      name = "quill-delta";
      packageName = "quill-delta";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/quill-delta/-/quill-delta-4.2.2.tgz";
        sha512 = "qjbn82b/yJzOjstBgkhtBjN2TNK+ZHP/BgUQO+j6bRhWQQdmj2lH6hXG7+nwwLF41Xgn//7/83lxs9n2BkTtTg==";
      };
    };
    "reflect-metadata-0.1.13" = {
      name = "reflect-metadata";
      packageName = "reflect-metadata";
      version = "0.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/reflect-metadata/-/reflect-metadata-0.1.13.tgz";
        sha512 = "Ts1Y/anZELhSsjMcU605fU9RE4Oi3p5ORujwbIKXfWa+0Zxs510Qrmrce5/Jowq3cHSZSJqBjypxmHarc+vEWg==";
      };
    };
    "remark-13.0.0" = {
      name = "remark";
      packageName = "remark";
      version = "13.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark/-/remark-13.0.0.tgz";
        sha512 = "HDz1+IKGtOyWN+QgBiAT0kn+2s6ovOxHyPAFGKVE81VSzJ+mq7RwHFledEvB5F1p4iJvOah/LOKdFuzvRnNLCA==";
      };
    };
    "remark-parse-9.0.0" = {
      name = "remark-parse";
      packageName = "remark-parse";
      version = "9.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-parse/-/remark-parse-9.0.0.tgz";
        sha512 = "geKatMwSzEXKHuzBNU1z676sGcDcFoChMK38TgdHJNAYfFtsfHDQG7MoJAjs6sgYMqyLduCYWDIWZIxiPeafEw==";
      };
    };
    "remark-stringify-9.0.1" = {
      name = "remark-stringify";
      packageName = "remark-stringify";
      version = "9.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-stringify/-/remark-stringify-9.0.1.tgz";
        sha512 = "mWmNg3ZtESvZS8fv5PTvaPckdL4iNlCHTt8/e/8oN08nArHRHjNZMKzA/YW3+p7/lYqIw4nx1XsjCBo/AxNChg==";
      };
    };
    "repeat-string-1.6.1" = {
      name = "repeat-string";
      packageName = "repeat-string";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz";
        sha1 = "8dcae470e1c88abc2d600fff4a776286da75e637";
      };
    };
    "tr46-0.0.3" = {
      name = "tr46";
      packageName = "tr46";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tr46/-/tr46-0.0.3.tgz";
        sha1 = "8184fd347dac9cdc185992f3a6622e14b9d9ab6a";
      };
    };
    "trough-1.0.5" = {
      name = "trough";
      packageName = "trough";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/trough/-/trough-1.0.5.tgz";
        sha512 = "rvuRbTarPXmMb79SmzEp8aqXNKcK+y0XaB298IXueQ8I2PsrATcPBCSPyK/dDNa2iWOhKlfNnOjdAOTBU/nkFA==";
      };
    };
    "unified-9.2.2" = {
      name = "unified";
      packageName = "unified";
      version = "9.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unified/-/unified-9.2.2.tgz";
        sha512 = "Sg7j110mtefBD+qunSLO1lqOEKdrwBFBrR6Qd8f4uwkhWNlbkaqwHse6e7QvD3AP/MNoJdEDLaf8OxYyoWgorQ==";
      };
    };
    "unist-util-stringify-position-2.0.3" = {
      name = "unist-util-stringify-position";
      packageName = "unist-util-stringify-position";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-stringify-position/-/unist-util-stringify-position-2.0.3.tgz";
        sha512 = "3faScn5I+hy9VleOq/qNbAd6pAx7iH5jYBMS9I1HgQVijz/4mv5Bvw5iw1sC/90CODiKo81G/ps8AJrISn687g==";
      };
    };
    "vfile-4.2.1" = {
      name = "vfile";
      packageName = "vfile";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vfile/-/vfile-4.2.1.tgz";
        sha512 = "O6AE4OskCG5S1emQ/4gl8zK586RqA3srz3nfK/Viy0UPToBc5Trp9BVFb1u0CjsKrAWwnpr4ifM/KBXPWwJbCA==";
      };
    };
    "vfile-message-2.0.4" = {
      name = "vfile-message";
      packageName = "vfile-message";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vfile-message/-/vfile-message-2.0.4.tgz";
        sha512 = "DjssxRGkMvifUOJre00juHoP9DPWuzjxKuMDrhNbk2TdaYYBNMStsNhEOt3idrtI12VQYM/1+iM0KOzXi4pxwQ==";
      };
    };
    "vscode-jsonrpc-5.0.1" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-5.0.1.tgz";
        sha512 = "JvONPptw3GAQGXlVV2utDcHx0BiY34FupW/kI6mZ5x06ER5DdPG/tXWMVHjTNULF5uKPOUUD0SaXg5QaubJL0A==";
      };
    };
    "vscode-jsonrpc-6.0.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-6.0.0.tgz";
        sha512 = "wnJA4BnEjOSyFMvjZdpiOwhSq9uDoK8e/kpRJDTaMYzwlkrhG1fwDIZI94CLsLzlCK5cIbMMtFlJlfR57Lavmg==";
      };
    };
    "vscode-languageserver-6.1.1" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "6.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-6.1.1.tgz";
        sha512 = "DueEpkUAkD5XTR4MLYNr6bQIp/UFR0/IPApgXU3YfCBCB08u2sm9hRCs6DxYZELkk++STPjpcjksR2H8qI3cDQ==";
      };
    };
    "vscode-languageserver-protocol-3.16.0" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.16.0.tgz";
        sha512 = "sdeUoAawceQdgIfTI+sdcwkiK2KU+2cbEYA0agzM2uqaUy2UpnnGHtWTHVEtS0ES4zHU0eMFRGN+oQgDxlD66A==";
      };
    };
    "vscode-languageserver-textdocument-1.0.4" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.4.tgz";
        sha512 = "/xhqXP/2A2RSs+J8JNXpiiNVvvNM0oTosNVmQnunlKvq9o4mupHOBAnnzH0lwIPKazXKvAKsVp1kr+H/K4lgoQ==";
      };
    };
    "vscode-languageserver-types-3.16.0" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.16.0.tgz";
        sha512 = "k8luDIWJWyenLc5ToFQQMaSrqCHiLwyKPHKPQZ5zz21vM+vIVUSvsRpcbiECH4WR88K2XZqc4ScRcZ7nk/jbeA==";
      };
    };
    "webidl-conversions-3.0.1" = {
      name = "webidl-conversions";
      packageName = "webidl-conversions";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/webidl-conversions/-/webidl-conversions-3.0.1.tgz";
        sha1 = "24534275e2a7bc6be7bc86611cc16ae0a5654871";
      };
    };
    "whatwg-url-5.0.0" = {
      name = "whatwg-url";
      packageName = "whatwg-url";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-url/-/whatwg-url-5.0.0.tgz";
        sha1 = "966454e8765462e37644d3626f6742ce8b70965d";
      };
    };
    "ws-7.5.7" = {
      name = "ws";
      packageName = "ws";
      version = "7.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.5.7.tgz";
        sha512 = "KMvVuFzpKBuiIXW3E4u3mySRO2/mCHSyZDJQM5NQ9Q9KHWHWh0NHgfbRMLLrceUK5qAL4ytALJbpRMjixFZh8A==";
      };
    };
    "zwitch-1.0.5" = {
      name = "zwitch";
      packageName = "zwitch";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/zwitch/-/zwitch-1.0.5.tgz";
        sha512 = "V50KMwwzqJV0NpZIZFwfOD5/lyny3WlSzRiXgA0G7VUnRlqttta1L6UQIHzd6EuBY/cHGfwTIck7w1yH6Q5zUw==";
      };
    };
  };
in
{
  "lsp-grammarly" = nodeEnv.buildNodePackage {
    name = "_at_emacs-grammarly_slash_unofficial-grammarly-language-server";
    packageName = "@emacs-grammarly/unofficial-grammarly-language-server";
    version = "0.2.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/@emacs-grammarly/unofficial-grammarly-language-server/-/unofficial-grammarly-language-server-0.2.2.tgz";
      sha512 = "ZRfz5O+LGl6Fn8gm0xfBk07mDz+NSa+82ev4Gi7qcDLKJ+IG2aDuia1CLZiQCDxo2U+XqZZWvnb9Zdsa5BEREg==";
    };
    dependencies = [
      sources."@emacs-grammarly/unofficial-grammarly-api-0.2.2"
      sources."@flatten-js/interval-tree-1.0.18"
      sources."@types/mdast-3.0.10"
      sources."@types/unist-2.0.6"
      sources."@vue/reactivity-3.2.31"
      sources."@vue/shared-3.2.31"
      sources."bail-1.0.5"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-1.1.11"
      sources."character-entities-1.2.4"
      sources."character-entities-legacy-1.1.4"
      sources."character-reference-invalid-1.1.4"
      sources."concat-map-0.0.1"
      sources."debug-4.3.3"
      sources."extend-3.0.2"
      sources."fast-diff-1.2.0"
      sources."inversify-5.1.1"
      sources."is-alphabetical-1.0.4"
      sources."is-alphanumerical-1.0.4"
      sources."is-buffer-2.0.5"
      sources."is-decimal-1.0.4"
      sources."is-hexadecimal-1.0.4"
      sources."is-plain-obj-2.1.0"
      sources."lodash.clonedeep-4.5.0"
      sources."lodash.isequal-4.5.0"
      sources."longest-streak-2.0.4"
      sources."mdast-util-from-markdown-0.8.5"
      sources."mdast-util-to-markdown-0.6.5"
      sources."mdast-util-to-string-2.0.0"
      sources."micromark-2.11.4"
      sources."minimatch-3.1.2"
      sources."ms-2.1.2"
      sources."node-fetch-2.6.7"
      sources."parse-entities-2.0.0"
      sources."quill-delta-4.2.2"
      sources."reflect-metadata-0.1.13"
      sources."remark-13.0.0"
      sources."remark-parse-9.0.0"
      sources."remark-stringify-9.0.1"
      sources."repeat-string-1.6.1"
      sources."tr46-0.0.3"
      sources."trough-1.0.5"
      sources."unified-9.2.2"
      sources."unist-util-stringify-position-2.0.3"
      sources."vfile-4.2.1"
      sources."vfile-message-2.0.4"
      sources."vscode-jsonrpc-5.0.1"
      sources."vscode-languageserver-6.1.1"
      (sources."vscode-languageserver-protocol-3.16.0" // {
        dependencies = [
          sources."vscode-jsonrpc-6.0.0"
        ];
      })
      sources."vscode-languageserver-textdocument-1.0.4"
      sources."vscode-languageserver-types-3.16.0"
      sources."webidl-conversions-3.0.1"
      sources."whatwg-url-5.0.0"
      sources."ws-7.5.7"
      sources."zwitch-1.0.5"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "LSP server implementation for Grammarly";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
